# Generated by Django 4.2.4 on 2024-05-31 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('acc_no', models.CharField(max_length=50)),
                ('cust_state', models.CharField(max_length=50)),
                ('cust_pin', models.CharField(max_length=6)),
                ('dpd', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
