# Generated by Django 4.2.4 on 2024-05-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_uploadeddata_uploadfile_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddata',
            old_name='data',
            new_name='date',
        ),
    ]
